#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

TOPKG=./pkg/pkg.ml

action ()
{
    case $1 in
        default)    $TOPKG build ;;
        test|tests) $TOPKG build && $TOPKG test ;;
        doc)        shift; $TOPKG doc --dev $* ;;
        api-doc)    shift; $TOPKG doc $* ;;
        clean)      $TOPKG clean ;;
        *)          $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
